# Generated by Django 5.1 on 2024-08-27 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_term', models.CharField(help_text='Palavra(s) chave da busca', max_length=100, verbose_name='termo de busca')),
                ('count', models.IntegerField(default=10, help_text='Número de resultados para retornar na resposta', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='quantidade')),
                ('offset', models.IntegerField(default=0, help_text='Número de respostas que serão puladas antes de retornar o resultado', validators=[django.core.validators.MinValueValidator(0)], verbose_name='offset')),
                ('mkt', models.CharField(choices=[('es-AR', 'Argentina'), ('en-AU', 'Austrália'), ('de-AT', 'Áustria'), ('nl-BE', 'Bélgica'), ('fr-BE', 'Bélgica'), ('pt-BR', 'Brasil'), ('en-CA', 'Canadá'), ('fr-CA', 'Canadá'), ('es-CL', 'Chile'), ('da-DK', 'Dinamarca'), ('fi-FI', 'Finlândia'), ('fr-FR', 'França'), ('de-DE', 'Alemanha'), ('zh-HK', 'Hong Kong SAR'), ('en-IN', 'Índia'), ('en-ID', 'Indonésia'), ('it-IT', 'Itália'), ('ja-JP', 'Japão'), ('ko-KR', 'Coreia'), ('en-MY', 'Malásia'), ('es-MX', 'México'), ('nl-NL', 'Países Baixos'), ('en-NZ', 'Nova Zelândia'), ('no-NO', 'Noruega'), ('zh-CN', 'República Popular da China'), ('pl-PL', 'Polônia'), ('en-PH', 'Filipinas'), ('ru-RU', 'Rússia'), ('en-ZA', 'África do Sul'), ('es-ES', 'Espanha'), ('sv-SE', 'Suécia'), ('fr-CH', 'Suíça'), ('de-CH', 'Suíça'), ('zh-TW', 'Taiwan'), ('tr-TR', 'Turquia'), ('en-GB', 'Reino Unido'), ('en-US', 'Estados Unidos'), ('es-US', 'Estados Unidos')], default='pt-BR', help_text='Mercado do qual os resultados serão buscados', max_length=5, verbose_name='mercado')),
                ('freshness', models.CharField(choices=[('Day', 'Dia'), ('Month', 'Mês'), ('Year', 'Ano')], default='Day', help_text='O quão recente as notícias retornadas devem ser', max_length=5, verbose_name='mais recentes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Busca',
                'verbose_name_plural': 'Buscas',
            },
        ),
    ]
