# Generated by Django 5.1 on 2024-08-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='título')),
                ('descripiton', models.TextField(verbose_name='descrição')),
                ('url', models.URLField(help_text='Link da notícia', unique=True, verbose_name='link')),
                ('date_published', models.DateTimeField(verbose_name='data de publicação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
        migrations.AlterField(
            model_name='query',
            name='query_term',
            field=models.CharField(help_text='Palavra(s) chave da busca', max_length=100, unique=True, verbose_name='termo de busca'),
        ),
    ]
