# Generated by Django 5.1 on 2024-08-27 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='descripiton',
            new_name='description',
        ),
    ]
