# Generated by Django 5.1 on 2024-08-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_descripiton_news_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_term',
            field=models.CharField(help_text='Palavra(s) chave da busca', max_length=100, verbose_name='termo de busca'),
        ),
        migrations.AddConstraint(
            model_name='query',
            constraint=models.UniqueConstraint(fields=('query_term', 'mkt'), name='query term and mkt must be unique together'),
        ),
    ]
