# Generated by Django 5.1 on 2024-08-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_query_query_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='mkt',
            field=models.CharField(choices=[('es-AR', 'Argentina'), ('en-AU', 'Austrália'), ('de-AT', 'Áustria'), ('nl-BE', 'Bélgica'), ('fr-BE', 'Bélgica'), ('pt-BR', 'Brasil'), ('en-CA', 'Canadá'), ('fr-CA', 'Canadá'), ('es-CL', 'Chile'), ('da-DK', 'Dinamarca'), ('fi-FI', 'Finlândia'), ('fr-FR', 'França'), ('de-DE', 'Alemanha'), ('zh-HK', 'Hong Kong SAR'), ('en-IN', 'Índia'), ('en-ID', 'Indonésia'), ('it-IT', 'Itália'), ('ja-JP', 'Japão'), ('ko-KR', 'Coreia'), ('en-MY', 'Malásia'), ('es-MX', 'México'), ('nl-NL', 'Países Baixos'), ('en-NZ', 'Nova Zelândia'), ('no-NO', 'Noruega'), ('zh-CN', 'República Popular da China'), ('pl-PL', 'Polônia'), ('en-PH', 'Filipinas'), ('ru-RU', 'Rússia'), ('en-ZA', 'África do Sul'), ('es-ES', 'Espanha'), ('sv-SE', 'Suécia'), ('fr-CH', 'Suíça'), ('de-CH', 'Suíça'), ('zh-TW', 'Taiwan'), ('tr-TR', 'Turquia'), ('en-GB', 'Reino Unido'), ('en-US', 'Estados Unidos'), ('es-US', 'Estados Unidos Espanhol')], default='pt-BR', help_text='Mercado do qual os resultados serão buscados', max_length=5, verbose_name='mercado'),
        ),
    ]
